### ISSUE TITLE
результати перевірки

### ISSUE THREAD

**Issue by Aqueelone** [9sasha6/git-repo#1]
Нижче наводяться результати перевірки.
Якщо з чимось не дуже згодні, наводьте свої контр аргументи, передивимося.

0. (SQL) 25 балів + 10 (перше завдання -- альтернативи) + 10 гарна організація тестових данних\оформлення
1. (Palindrome) 20 балів
(Зауважте, що алгоритм через реверс не дуже вдалий, окрім того, для тестів правильний стиль коли перевіряються всі можливі варіант, у тому числі критичні... Раджу подивитися -- в наборі книг, що ми висилали є гарна книга з цієї теми -- "Тестування в Андроід" -- там половина -- сама теорія тестів, де гарно розповідається що, чому і нащо...)
2. (Complimentary) 25 балів + 10 гарний алгоритм
3. (bigdata) 30 балів + 10 оформлення + 10 гарний алгоритм + 10 гарні тести
4. (cacheMap) 50 балів + 10 оформлення + 10 гарний алгоритм + 10 гарні тести + 10 вміння працювати з джерелами інформації
5. (testerFib) 80 балів + 10 оформлення + 10 гарний алгоритм
8. (social) 40 балів
(Це завдання на жаль виконано частково, але йшли у правильному напрямку...)

**Comment by 9sasha6** [comment]
Дякую за перевірку , ще хотілося б дізнатись,  коли будуть відомі списки тих хто пройшов?

**Comment by 9sasha6** [comment]
Не могли би ви перепровірити завдання з логінення в улюблену соц. мережу ,
ви написали , що я недокінця виконав завдання. Додаю скріни роботи додатка

2017-03-20 17:14 GMT+02:00 <9torchuncky6@gmail.com>:

**Comment by Aqueelone** [comment]
Так, все добре... тільки "додаток до соціальної мережі" "за означенням" включає той факт, що хоча б певна частина функціоналу соціальної мережі відпрацьовується... Ви гарно все зробили, тільки треба було ще хоча б частину функції відпрацювати -- наприклад, стрічку активності чи щось таке...
Тому, зауважте, 80 відсотків виконання завдання зараховано...

**Comment by 9sasha6** [comment]
Зрозумів, згідний,  дякую за відповідь.
